### ISSUE TITLE
Lỗi khi cài đặt judge

### ISSUE THREAD

**Issue by phuleethanh** [VNOI-Admin/judge-server#31]
Khi tiến hành cài đặt judge, khi chạy lệnh make judge-tiervnoj thì báo lỗi như sau:
 > [2/4] RUN apt-get update &&  apt-get install -y --no-install-recommends openjdk-19-jdk-headless openjdk-19-jre-headless unzip jq &&     rm -rf /var/lib/apt/lists/*:               
#0 0.562 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]                    
#0 0.582 Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]                                                                                       
#0 0.694 Ign:3 http://security.debian.org/debian-security stretch/updates InRelease
#0 0.761 Err:4 http://security.debian.org/debian-security stretch/updates Release
#0 0.761   404  Not Found [IP: 151.101.130.132 80]
#0 0.871 Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [237 kB]
#0 0.943 Get:6 http://deb.debian.org/debian sid InRelease [184 kB]
#0 1.279 Get:7 http://deb.debian.org/debian experimental InRelease [101 kB]
#0 1.345 Ign:8 http://deb.debian.org/debian stretch InRelease
#0 1.402 Get:9 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
#0 1.687 Get:10 http://deb.debian.org/debian sid/main amd64 Packages [9436 kB]
#0 1.997 Err:11 http://deb.debian.org/debian stretch Release
#0 1.997   404  Not Found [IP: 151.101.78.132 80]
#0 2.058 Get:12 http://deb.debian.org/debian experimental/main amd64 Packages [833 kB]
#0 4.060 Reading package lists...
#0 5.516 E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#0 5.516 E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
------
ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends openjdk-19-jdk-headless openjdk-19-jre-headless unzip jq &&        rm -rf /var/lib/apt/lists/*]: exit code: 100
make: *** [Makefile:18: judge-tiervnoj] Error 1

Rất mong admin hỗ trợ sửa lỗi này, cảm ơn.

**Comment by phuleethanh** [comment]
docker của dmoj thì make tier1,2,3 bình thường

**Comment by phuleethanh** [comment]
Sau khi mày mò, mình sửa thế này và nó đã hoạt động: https://ideone.com/13y0z0

**Comment by hieplpvip** [comment]
Should be fixed now
