### ISSUE TITLE
judge-server Fail scratch

### ISSUE THREAD

**Issue by Cuongyd196** [VNOI-Admin/judge-server#36]
Vấn đề deploy scratch-run cho dmoj
Mình đã làm theo hướng dẫn và khi run bằng docker có hiển thị đã run thành công scratch trên terminal nhưng trên web máy chấm ko hiển thị scratch.
![image](https://github.com/VNOI-Admin/judge-server/assets/62423513/2715ef09-2054-4789-ba33-90641d9c6903)

- File cấu hình đã có scracth:
![image](https://github.com/VNOI-Admin/judge-server/assets/62423513/54208f88-9d27-4b87-9d69-70c89251ea1a)

- Trên web không hiển thị scratch:
![image](https://github.com/VNOI-Admin/judge-server/assets/62423513/e4e35e70-9921-410e-b89b-7369ed2d148a)

Nhờ team hỗ trợ mình. Thanks all.

**Comment by hieplpvip** [comment]
Hi anh. Để chấm Scratch thì phải dùng site của VNOI ạ. Theo trong hình thì hình như anh đang dùng bản gốc của DMOJ

**Comment by Cuongyd196** [comment]
> Hi anh. Để chấm Scratch thì phải dùng site của VNOI ạ. Theo trong hình thì hình như anh đang dùng bản gốc của DMOJ

Ra là thế. Thanks bạn nhé
